#ifndef mip_widgets_included
#define mip_widgets_included
//----------------------------------------------------------------------

#include "mip.h"

#include "gui/widgets/mip_button_row_widget.h"
#include "gui/widgets/mip_button_widget.h"
#include "gui/widgets/mip_cached_widget.h"
#include "gui/widgets/mip_cairo_widget.h"
#include "gui/widgets/mip_circular_waveform_widget.h"
#include "gui/widgets/mip_container_widget.h"
#include "gui/widgets/mip_curve_widget.h"
#include "gui/widgets/mip_drag_value_widget.h"
#include "gui/widgets/mip_drag_value2_widget.h"
#include "gui/widgets/mip_dual_slider_widget.h"
//#include "gui/widgets/mip_graph_widget.h"
#include "gui/widgets/mip_grid_widget.h"
#include "gui/widgets/mip_group_box_widget.h"
//#include "gui/widgets/mip_image_strip_widget.h"
//#include "gui/widgets/mip_image_widget.h"
#include "gui/widgets/mip_keyboard_widget.h"
#include "gui/widgets/mip_knob2_widget.h"
#include "gui/widgets/mip_knob3_widget.h"
#include "gui/widgets/mip_knob4_widget.h"
#include "gui/widgets/mip_knob_widget.h"
#include "gui/widgets/mip_main_menu_widget.h"
#include "gui/widgets/mip_menu_item_widget2.h"
#include "gui/widgets/mip_menu_item_widget.h"
#include "gui/widgets/mip_menu_widget2.h"
#include "gui/widgets/mip_menu_widget.h"
#include "gui/widgets/mip_modmatrix_widget.h"
#include "gui/widgets/mip_pages_widget.h"
#include "gui/widgets/mip_panel_widget.h"
#include "gui/widgets/mip_plot_widget.h"
#include "gui/widgets/mip_range_slider_widget.h"
//#include "gui/widgets/mip_saheader_widget.h"
#include "gui/widgets/mip_scroll_bar_widget.h"
#include "gui/widgets/mip_scroll_box_widget.h"
#include "gui/widgets/mip_selector_widget.h"
#include "gui/widgets/mip_sizer_widget.h"
#include "gui/widgets/mip_slider_bank_widget.h"
#include "gui/widgets/mip_slider_widget.h"
#include "gui/widgets/mip_symbol_widget.h"
#include "gui/widgets/mip_tabs_widget.h"
#include "gui/widgets/mip_template_widget.h"
#include "gui/widgets/mip_text_box_widget.h"
#include "gui/widgets/mip_text_edit_widget.h"
#include "gui/widgets/mip_text_widget.h"
#include "gui/widgets/mip_timeline_widget.h"
#include "gui/widgets/mip_value_graph_widget.h"
#include "gui/widgets/mip_value_widget.h"
#include "gui/widgets/mip_waveform_widget.h"

//----------------------------------------------------------------------
#endif
